name: QuadDump

settings:
  DEVELOPMENT_TEAM: 67762NVFY8
  PRODUCT_BUNDLE_IDENTIFIER: wakewakame.iOSplayground
  CODE_SIGN_STYLE: Automatic

targets:
  QuadDump:
    sources: QuadDump
    platform: iOS
    type: application
